**Task3_Images_from_1m**

In [2]:
import numpy as np
import cv2

In [27]:
calibration_images = []

#Image paths for 10 images named 1.jpeg to 10.jpeg
image_paths = [f'/content/{i}.jpeg' for i in range(10)]

# Loading and appending each image to the calibration_images list
for idx, path in enumerate(image_paths, 1):
    img = cv2.imread(path)
    if img is not None:
        calibration_images.append(img)

In [28]:
# Grid dimensions for the checkerboard pattern
grid_rows = 8
grid_cols = 8

# 3D object points and 2D image points
real_world_points = []
projected_image_points = []

# 3D points for the checkerboard pattern (Z=0 for all points)
grid_3d_points = np.zeros((grid_rows * grid_cols, 3), np.float32)
grid_3d_points[:, :2] = np.indices((grid_cols, grid_rows)).T.reshape(-1, 2)

In [29]:
for image in calibration_images:
    # Image to grayscale
    grayscale_image = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    # Detecting the chessboard corners
    success, corner_points = cv2.findChessboardCorners(grayscale_image, (grid_cols, grid_rows), None)

    # If corners are found, store the 3D and 2D points
    if success:
        real_world_points.append(grid_3d_points)
        projected_image_points.append(corner_points)

In [30]:
image_dimensions = grayscale_image.shape[::-1]

# Camera calibration process
calibration_status, intrinsic_matrix, distortion_coeffs, rotation_vectors, translation_vectors = cv2.calibrateCamera(
    real_world_points, projected_image_points, image_dimensions, None, None)

# Extract the first two distortion parameters
distortion_param_1, distortion_param_2, *_ = distortion_coeffs.flatten()

In [31]:
# Intrinsic camera matrix
print("Intrinsic Matrix parameter(K):")
print(intrinsic_matrix)

# First two distortion coefficients
print("Distortion Coefficients (k1, k2):")
print(distortion_param_1, distortion_param_2)

Intrinsic Matrix parameter(K):
[[2.26491561e+03 0.00000000e+00 1.28324475e+03]
 [0.00000000e+00 2.27353741e+03 8.90856990e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]
Distortion Coefficients (k1, k2):
-0.008142203590221605 -1.3203650369970834
